using System;
using System.Collections.Generic;
using System.Globalization;

namespace RyzenQuietPro
{
    public static class Loc
    {
        public static readonly (string Code, string Name, string Flag)[] SupportedLanguages = new[]
        {
            ("ru", "Русский", "🇷🇺"),
            ("en", "English", "🇬🇧"),
            ("de", "Deutsch", "🇩🇪"),
            ("es", "Español", "🇪🇸"),
            ("fr", "Français", "🇫🇷"),
            ("ja", "日本語", "🇯🇵"),
            ("pt", "Português", "🇵🇹"),
            ("zh", "中文", "🇨🇳")
        };

        private static string _currentLang = "en";

        public static string CurrentLanguage => _currentLang;

        public static event Action? LanguageChanged;

        private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
        {
            ["ru"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "Тихий",
                ["SilentFull"] = "🌿 Тихий (99%)",
                ["Boost"] = "Турбо",
                ["BoostActive"] = "⚡ Турбо (100%)",
                ["Threads"] = "потоков",
                ["ThreadsActive"] = "потоков активно",
                ["AllDisksIdle"] = "Все накопители в простое",
                ["Idle"] = "Простой",
                ["ShowAllGpus"] = "Все GPU",
                
                // Headers
                ["Cpu"] = "CPU",
                ["Ram"] = "RAM",
                ["Gpu"] = "GPU",
                ["Vram"] = "VRAM",
                ["Disk"] = "DISK",
                ["Fans"] = "КУЛЕРЫ",
                ["Stopwatch"] = "СЕКУНДОМЕР",
                ["StopwatchModule"] = "⏱️ Секундомер",
                ["StopwatchStart"] = "▶ Старт",
                ["StopwatchStop"] = "⏸ Стоп",
                ["StopwatchReset"] = "↺ Сброс",
                ["StopwatchAuto"] = "⚡ Авто",
                ["StopwatchAutoFull"] = "Автостарт",
                ["StopwatchRunning"] = "Идёт отсчёт",
                ["StopwatchStopped"] = "Остановлен",
                ["StopwatchArmed"] = "Авто-мониторинг",
                ["StopwatchSettings"] = "Секундомер и Автостарт",
                ["StopwatchEnable"] = "Включить модуль секундомера",
                ["StopwatchAutoStartEnable"] = "Автостарт по мощности",
                ["StopwatchTriggerSource"] = "Критерий автостарта:",
                ["StopwatchSourceMax"] = "Любой (Max)",
                ["StopwatchSourceCpu"] = "CPU",
                ["StopwatchSourceGpu"] = "GPU",
                ["StopwatchSourceTotal"] = "CPU + GPU",
                ["StopwatchDescCpu"] = "⚡ Старт если мощность CPU > {0}W",
                ["StopwatchDescGpu"] = "⚡ Старт если мощность GPU > {0}W",
                ["StopwatchDescTotal"] = "⚡ Старт если сумма CPU+GPU > {0}W",
                ["StopwatchDescMax"] = "⚡ Старт если CPU > {0}W или GPU > {0}W",
                ["StopwatchAutoStartWatts"] = "Порог автостарта",
                ["StopwatchAutoStopWatts"] = "Порог автостопа",
                ["StopwatchHysteresis"] = "Гистерезис (задержка)",
                ["StopwatchHysteresisTip"] = "Задержка остановки при кратковременном падении мощности (смена сцен, загрузка)",
                ["Sec"] = "сек",
                
                // Tooltips
                ["TipInfo"] = "Характеристики системы и совместимость",
                ["TipPinOn"] = "Поверх окон (Вкл)",
                ["TipPinOff"] = "Поверх окон (Выкл)",
                ["TipDetach"] = "Открепить виджет на рабочий стол",
                ["TipDock"] = "Прикрепить к панели задач",
                ["TipClose"] = "Свернуть в трей",
                
                // Menu: Graphs
                ["MenuGraphs"] = "Графики и модули:",
                ["CpuGraph"] = "📊 График CPU (Загрузка)",
                ["CpuCores"] = "🔳 Матрица ядер CPU (16/32)",
                ["TopProcesses"] = "⚡ Топ-5 процессов по CPU",
                ["RamGraph"] = "🧠 График RAM (Память)",
                ["GpuGraph"] = "🎮 График GPU (Видеокарта)",
                ["GpuTemp"] = "🌡️ Линия температуры GPU",
                ["GpuFan"] = "💨 Обороты кулеров GPU",
                ["VramGraph"] = "📼 График VRAM (Видеопамять)",
                ["DiskGraph"] = "💽 График Дисков (SSD/HDD)",
                ["FanGraph"] = "❄️ График кулеров (RPM) [Дополнение]",
                ["ShowAllGraphs"] = "Показать все графики",
                
                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• Активно",
                ["FanPluginStatus_Connecting"] = "• Подключение...",
                ["FanPluginStatus_NotInstalled"] = "⚪ Дополнение не найдено",
                ["FanPluginStatus_Disabled"] = "Выключено",
                ["FanPluginStatus_NeedAdmin"] = "🟡 Требуются права Администратора",
                ["FanPluginStatus_NoFans"] = "Датчики кулеров не найдены (EC заблокирован)",
                ["FanPluginFolder"] = "Папка дополнения",
                ["FanPlugin_Start"] = "▶ Старт",
                ["FanPlugin_Stop"] = "⏹ Стоп",
                ["FanPlugin_Stopped"] = "⚪ Остановлено",
                ["FanPlugin_TipToggle"] = "Запуск / остановка фонового дополнения кулеров",
                ["FanVisualMode_Graph"] = "📈 График",
                ["FanVisualMode_Icons"] = "🌀 В 1 ряд",
                ["FanVisualMode_Grid"] = "▦ Сетка",
                ["FanDemoMode"] = "👁️ Демо",
                ["FanDemoModeHint"] = "Эмуляция (тест дизайна)",
                ["FanDemoModeTooltip"] = "Эмуляция вентиляторов для тестирования интерфейса (синтетические данные). На ноутбуках кулеры управляются EC и недоступны в ОС.",
                ["FanLargeIcons"] = "Большой размер",
                ["FanLargeIconsTip"] = "Увеличить размер вертушек кулеров в 2 раза",
                ["FanScale"] = "Размер вертушек",
                ["FanScaleTip"] = "Настройка масштаба вертушек кулеров (100% — 200%)",
                ["FanSelectFans"] = "⚙ Выбор",
                ["FanSelectFansFull"] = "⚙ Выбор кулеров",
                ["FanSelectionTitle"] = "Отображаемые кулеры",
                ["FanSelectionHint"] = "Отметьте кулеры для отображения в виджете. Кулеры с 0 RPM можно оставить включенными — они заработают при нагрузке.",
                ["FanSelectAll"] = "Выбрать все",
                ["FanDeselectAll"] = "Снять все",
                ["FanSelectionNoLiveFans"] = "Вентиляторы не обнаружены. Запустите службу кулеров.",
                ["FanGpuSpinTest"] = "⚡ Тест кулеров GPU (10с)",
                ["FanGpuSpinTesting"] = "⏳ Тестирование (10с)...",
                
                // Menu: Settings
                ["MenuSettings"] = "Настройки системы:",
                ["AlwaysOnTop"] = "📌 Поверх всех окон",
                ["AutoQuiet"] = "🌿 Тихий режим при простое (5 мин)",
                ["Startup"] = "🚀 Запуск вместе с Windows",
                ["TrayIconMenu"] = "🏷️ Иконка в трее",
                ["TrayMetricCpu"] = "CPU % (Процессор)",
                ["TrayMetricGpu"] = "GPU % (Видеокарта)",
                ["TrayMetricRam"] = "RAM % (Память)",
                ["TrayMetricNone"] = "Стандартная иконка",
                ["TrayMetricNoneShort"] = "Иконка",
                ["BtnSpecsShort"] = "ℹ Характеристики",
                ["Opacity"] = "👁️ Прозрачность окна",
                ["Language"] = "🌐 Язык (Language)",
                ["HardwareInfo"] = "ℹ Характеристики системы",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ Выход",

                // Info Dialog
                ["InfoTitle"] = "Характеристики системы и поддержка",
                ["InfoDetected"] = "💻 ОБНАРУЖЕНО В СИСТЕМЕ",
                ["InfoSupported"] = "🚀 ПОДДЕРЖИВАЕМЫЕ АРХИТЕКТУРЫ",
                ["InfoClose"] = "Закрыть",
                ["SysMemory"] = "Системная память",
                ["DedMemory"] = "Выделенная видеопамять",
                ["PhysicalDrives"] = "Физических накопителей",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 Тихий (99%)",
                ["CpuSilent"] = "CPU: 🌿 Тихий",
                ["CpuBoostActive"] = "CPU: ⚡ Турбо (100%)",
                ["CpuBoost"] = "CPU: ⚡ Турбо",
                ["GpuSilentFull"] = "GPU: 🌿 Тихий ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 Тихий",
                ["GpuBoostActive"] = "GPU: ⚡ Турбо ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ Турбо ({0}W)",
                ["TipGpuTuning"] = "Настройка мощности и кулеров GPU",
                ["GpuTuningTitle"] = "Тюнинг GPU (Акустика и мощность)",
                ["GpuTuningEnable"] = "Включить тюнинг GPU",
                ["SeparateCpuGpu"] = "Раздельное управление тишиной CPU и GPU",
                ["GpuPowerLimit"] = "Лимит мощности в тихом режиме",
                ["GpuPowerLimitTip"] = "Ограничение TDP видеокарты для снижения нагрева и шума кулеров под нагрузкой",
                ["GpuFanCapEnable"] = "Акустический лимит кулеров GPU",
                ["GpuFanCap"] = "Макс. обороты кулеров в тихом режиме",
                ["GpuFanCapTip"] = "Ограничение максимальной скорости вентиляторов GPU",
                ["GpuFailSafeInfo"] = "🛡 Защита: авто-сброс лимита кулеров при {0}°C",
                ["GpuPresetEco"] = "Эко",
                ["GpuPresetQuiet"] = "Тихий",
                ["GpuPresetBalanced"] = "Баланс",
                ["GpuPresetStock"] = "Стандарт"
            },
            ["en"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "Silent",
                ["SilentFull"] = "🌿 Silent (99%)",
                ["Boost"] = "Boost",
                ["BoostActive"] = "⚡ Boost ON (100%)",
                ["Threads"] = "Threads",
                ["ThreadsActive"] = "Threads Active",
                ["AllDisksIdle"] = "All Disks Idle",
                ["Idle"] = "Idle",
                ["ShowAllGpus"] = "Show all",

                ["Cpu"] = "CPU",
                ["Ram"] = "RAM",
                ["Gpu"] = "GPU",
                ["Vram"] = "VRAM",
                ["Disk"] = "DISK",
                ["Fans"] = "FANS",
                ["Stopwatch"] = "STOPWATCH",
                ["StopwatchModule"] = "⏱️ Stopwatch",
                ["StopwatchStart"] = "▶ Start",
                ["StopwatchStop"] = "⏸ Stop",
                ["StopwatchReset"] = "↺ Reset",
                ["StopwatchAuto"] = "⚡ Auto",
                ["StopwatchAutoFull"] = "Auto-Start",
                ["StopwatchRunning"] = "Running",
                ["StopwatchStopped"] = "Stopped",
                ["StopwatchArmed"] = "Auto-monitoring",
                ["StopwatchSettings"] = "Stopwatch & Auto-Start",
                ["StopwatchEnable"] = "Enable stopwatch module",
                ["StopwatchAutoStartEnable"] = "Auto-start by power load",
                ["StopwatchTriggerSource"] = "Auto-start criterion:",
                ["StopwatchSourceMax"] = "Any (Max)",
                ["StopwatchSourceCpu"] = "CPU",
                ["StopwatchSourceGpu"] = "GPU",
                ["StopwatchSourceTotal"] = "CPU + GPU",
                ["StopwatchDescCpu"] = "⚡ Starts when CPU power > {0}W",
                ["StopwatchDescGpu"] = "⚡ Starts when GPU power > {0}W",
                ["StopwatchDescTotal"] = "⚡ Starts when total power (CPU+GPU) > {0}W",
                ["StopwatchDescMax"] = "⚡ Starts when either CPU > {0}W or GPU > {0}W",
                ["StopwatchAutoStartWatts"] = "Auto-start threshold",
                ["StopwatchAutoStopWatts"] = "Auto-stop threshold",
                ["StopwatchHysteresis"] = "Hysteresis delay",
                ["StopwatchHysteresisTip"] = "Delay before stopping when power drops briefly (loading screens, transitions)",
                ["Sec"] = "sec",

                ["TipInfo"] = "System Specs & Hardware Support",
                ["TipPinOn"] = "Always On Top (Pinned)",
                ["TipPinOff"] = "Always On Top (Unpinned)",
                ["TipDetach"] = "Detach Floating Widget",
                ["TipDock"] = "Dock to Tray",
                ["TipClose"] = "Hide to Tray",

                ["MenuGraphs"] = "Graphs & Modules:",
                ["CpuGraph"] = "📊 CPU Load Graph",
                ["CpuCores"] = "🔳 CPU Cores Heatmap (16/32)",
                ["TopProcesses"] = "⚡ Top 5 CPU Processes",
                ["RamGraph"] = "🧠 RAM Usage Graph",
                ["GpuGraph"] = "🎮 GPU Load Graph",
                ["GpuTemp"] = "🌡️ GPU Temperature Curve",
                ["GpuFan"] = "💨 GPU Fan Speed",
                ["VramGraph"] = "📼 VRAM Usage Graph",
                ["DiskGraph"] = "💽 Disk Activity Graph (SSD/HDD)",
                ["FanGraph"] = "❄️ Fan Speed Graph (RPM) [Addon]",
                ["ShowAllGraphs"] = "Show All Graphs",

                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• Active",
                ["FanPluginStatus_Connecting"] = "• Connecting...",
                ["FanPluginStatus_NotInstalled"] = "⚪ Addon not found",
                ["FanPluginStatus_Disabled"] = "Disabled",
                ["FanPluginStatus_NeedAdmin"] = "🟡 Admin rights required",
                ["FanPluginStatus_NoFans"] = "No fan sensors found (EC locked by vendor)",
                ["FanPluginFolder"] = "Addon folder",
                ["FanPlugin_Start"] = "▶ Start",
                ["FanPlugin_Stop"] = "⏹ Stop",
                ["FanPlugin_Stopped"] = "⚪ Stopped",
                ["FanPlugin_TipToggle"] = "Start / Stop background fan service addon",
                ["FanVisualMode_Graph"] = "📈 Graph",
                ["FanVisualMode_Icons"] = "🌀 1 Row",
                ["FanVisualMode_Grid"] = "▦ Grid",
                ["FanDemoMode"] = "👁️ Demo",
                ["FanDemoModeHint"] = "Emulation (UI preview)",
                ["FanDemoModeTooltip"] = "Fan emulation for UI testing (synthetic data). On laptops, fans are controlled by EC firmware and are not exposed to the OS.",
                ["FanLargeIcons"] = "Large Size",
                ["FanLargeIconsTip"] = "Increase cooler fan spinner icon size by ~2x",
                ["FanScale"] = "Fan Size",
                ["FanScaleTip"] = "Adjust fan spinner scale (100% — 200%)",
                ["FanSelectFans"] = "⚙ Fans",
                ["FanSelectFansFull"] = "⚙ Select Fans",
                ["FanSelectionTitle"] = "Displayed Coolers",
                ["FanSelectionHint"] = "Select which fans to display in the widget. Idle 0 RPM fans can remain enabled — they will spin up under load.",
                ["FanSelectAll"] = "Select All",
                ["FanDeselectAll"] = "Clear All",
                ["FanSelectionNoLiveFans"] = "No fan sensors detected. Start fan service to scan.",
                ["FanGpuSpinTest"] = "⚡ Test GPU Fans (10s)",
                ["FanGpuSpinTesting"] = "⏳ Testing (10s)...",
 
                ["MenuSettings"] = "System Settings:",
                ["AlwaysOnTop"] = "📌 Always On Top",
                ["AutoQuiet"] = "🌿 Auto-Quiet on Idle (5 min)",
                ["Startup"] = "🚀 Start with Windows",
                ["TrayIconMenu"] = "🏷️ Dynamic Tray Icon",
                ["TrayMetricCpu"] = "CPU % (Processor)",
                ["TrayMetricGpu"] = "GPU % (Graphics)",
                ["TrayMetricRam"] = "RAM % (Memory)",
                ["TrayMetricNone"] = "Standard Status Icon",
                ["TrayMetricNoneShort"] = "Icon",
                ["BtnSpecsShort"] = "ℹ System Specs",
                ["Opacity"] = "👁️ Window Opacity",
                ["Language"] = "🌐 Language",
                ["HardwareInfo"] = "ℹ System Specs & Hardware",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ Exit",

                ["InfoTitle"] = "Hardware Support & System Specs",
                ["InfoDetected"] = "💻 DETECTED ON YOUR SYSTEM",
                ["InfoSupported"] = "🚀 SUPPORTED HARDWARE ARCHITECTURES",
                ["InfoClose"] = "Close",
                ["SysMemory"] = "System Memory",
                ["DedMemory"] = "Dedicated Video Memory",
                ["PhysicalDrives"] = "Physical Drives",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 Silent (99%)",
                ["CpuSilent"] = "CPU: 🌿 Silent",
                ["CpuBoostActive"] = "CPU: ⚡ Boost (100%)",
                ["CpuBoost"] = "CPU: ⚡ Boost",
                ["GpuSilentFull"] = "GPU: 🌿 Silent ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 Silent",
                ["GpuBoostActive"] = "GPU: ⚡ Boost ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ Boost ({0}W)",
                ["TipGpuTuning"] = "GPU Power & Acoustic Tuning",
                ["GpuTuningTitle"] = "GPU Acoustic & Power Tuning (NVIDIA)",
                ["GpuTuningEnable"] = "Enable GPU Acoustic & Power Tuning",
                ["SeparateCpuGpu"] = "Separate CPU & GPU Silent Control",
                ["GpuPowerLimit"] = "Quiet Mode Power Limit",
                ["GpuPowerLimitTip"] = "Limits GPU power draw to drastically reduce heat and fan noise under load",
                ["GpuFanCapEnable"] = "Acoustic GPU Fan Cap",
                ["GpuFanCap"] = "Max Fan Speed in Quiet Mode",
                ["GpuFanCapTip"] = "Cap maximum GPU fan speed for whisper-quiet operation",
                ["GpuFailSafeInfo"] = "🛡 Safety Fail-Safe: auto-releases fan cap at {0}°C",
                ["GpuPresetEco"] = "Eco",
                ["GpuPresetQuiet"] = "Quiet",
                ["GpuPresetBalanced"] = "Balanced",
                ["GpuPresetStock"] = "Stock"
            },
            ["de"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "Leise",
                ["SilentFull"] = "🌿 Leise (99%)",
                ["Boost"] = "Boost",
                ["BoostActive"] = "⚡ Boost AN (100%)",
                ["Threads"] = "Threads",
                ["ThreadsActive"] = "Threads Aktiv",
                ["AllDisksIdle"] = "Alle Laufwerke im Leerlauf",
                ["Idle"] = "Leerlauf",
                ["ShowAllGpus"] = "Alle GPUs",

                ["Cpu"] = "CPU",
                ["Ram"] = "RAM",
                ["Gpu"] = "GPU",
                ["Vram"] = "VRAM",
                                ["Disk"] = "DATENTRÄGER",
                ["Fans"] = "LÜFTER",

                ["TipInfo"] = "Systemdaten & Hardware-Unterstützung",
                ["TipPinOn"] = "Immer im Vordergrund (Aktiv)",
                ["TipPinOff"] = "Immer im Vordergrund (Inaktiv)",
                ["TipDetach"] = "Als Desktop-Widget lösen",
                ["TipDock"] = "An Taskleiste andocken",
                ["TipClose"] = "In Infobereich minimieren",

                ["MenuGraphs"] = "Diagramme & Module:",
                ["CpuGraph"] = "📊 CPU-Auslastungsdiagramm",
                ["CpuCores"] = "🔳 CPU-Kerne Heatmap",
                ["TopProcesses"] = "⚡ Top 5 CPU-Prozesse",
                ["RamGraph"] = "🧠 RAM-Auslastung",
                ["GpuGraph"] = "🎮 GPU-Auslastung",
                ["GpuTemp"] = "🌡️ GPU-Temperaturkurve",
                ["GpuFan"] = "💨 GPU-Lüftergeschwindigkeit",
                ["VramGraph"] = "📼 VRAM-Diagramm",
                ["DiskGraph"] = "💽 Festplatten-Aktivität (SSD/HDD)",
                ["FanGraph"] = "❄️ Lüfter-Geschwindigkeit (RPM) [Addon]",
                ["ShowAllGraphs"] = "Alle Diagramme anzeigen",

                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• Aktiv",
                ["FanPluginStatus_Connecting"] = "• Verbindung...",
                ["FanPluginStatus_NotInstalled"] = "⚪ Addon nicht gefunden",
                ["FanPluginStatus_Disabled"] = "Deaktiviert",
                ["FanPluginStatus_NeedAdmin"] = "🟡 Administratorrechte erforderlich",
                ["FanPluginStatus_NoFans"] = "Keine Lüftersensoren gefunden (EC herstellergesperrt)",
                ["FanPluginFolder"] = "Addon-Ordner",
                ["FanPlugin_Start"] = "▶ Start",
                ["FanPlugin_Stop"] = "⏹ Stopp",
                ["FanPlugin_Stopped"] = "⚪ Gestoppt",
                ["FanPlugin_TipToggle"] = "Hintergrunddienst für Lüfter starten / stoppen",
                ["FanVisualMode_Graph"] = "📈 Diagramm",
                ["FanVisualMode_Icons"] = "🌀 1 Reihe",
                ["FanVisualMode_Grid"] = "▦ Raster",
                ["FanDemoMode"] = "👁️ Demo",
                ["FanDemoModeHint"] = "Emulation (UI-Vorschau)",
                ["FanDemoModeTooltip"] = "Lüfteremulation zur UI-Vorschau (synthetische Daten). Auf Laptops werden Lüfter vom EC gesteuert.",
                ["FanLargeIcons"] = "Große Symbole",
                ["FanLargeIconsTip"] = "Lüftersymbole um das 2-fache vergrößern",
                ["FanScale"] = "Lüftergröße",
                ["FanScaleTip"] = "Lüfterskalierung anpassen (100% — 200%)",
                ["FanSelectFans"] = "⚙ Lüfter",
                ["FanSelectFansFull"] = "⚙ Lüfter auswählen",
                ["FanSelectionTitle"] = "Angezeigte Lüfter",
                ["FanSelectionHint"] = "Wählen Sie die im Widget anzuzeigenden Lüfter aus. Lüfter mit 0 RPM können aktiv bleiben — sie laufen unter Last an.",
                ["FanSelectAll"] = "Alle auswählen",
                ["FanDeselectAll"] = "Auswahl aufheben",
                ["FanSelectionNoLiveFans"] = "Keine Lüftersensoren erkannt. Starten Sie den Lüfterdienst.",
                ["FanGpuSpinTest"] = "⚡ GPU-Lüftertest (10s)",
                ["FanGpuSpinTesting"] = "⏳ Test läuft (10s)...",

                ["MenuSettings"] = "Systemeinstellungen:",
                ["AlwaysOnTop"] = "📌 Immer im Vordergrund",
                ["AutoQuiet"] = "🌿 Auto-Leise bei Leerlauf (5 Min.)",
                ["Startup"] = "🚀 Mit Windows starten",
                ["TrayIconMenu"] = "🏷️ Dynamisches Tray-Icon",
                ["TrayMetricCpu"] = "CPU %",
                ["TrayMetricGpu"] = "GPU %",
                ["TrayMetricRam"] = "RAM %",
                ["TrayMetricNone"] = "Standard-Icon",
                ["TrayMetricNoneShort"] = "Icon",
                ["BtnSpecsShort"] = "ℹ Systemdaten",
                ["Opacity"] = "👁️ Fenster-Transparenz",
                ["Language"] = "🌐 Sprache / Language",
                ["HardwareInfo"] = "ℹ Systeminformationen",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ Beenden",

                ["InfoTitle"] = "Hardware-Unterstützung & Systemdaten",
                ["InfoDetected"] = "💻 IM SYSTEM ERKANNT",
                ["InfoSupported"] = "🚀 UNTERSTÜTZTE ARCHITEKTUREN",
                ["InfoClose"] = "Schließen",
                ["SysMemory"] = "Systemspeicher",
                ["DedMemory"] = "Dedizierter Videospeicher",
                ["PhysicalDrives"] = "Physische Laufwerke",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 Leise (99%)",
                ["CpuSilent"] = "CPU: 🌿 Leise",
                ["CpuBoostActive"] = "CPU: ⚡ Boost (100%)",
                ["CpuBoost"] = "CPU: ⚡ Boost",
                ["GpuSilentFull"] = "GPU: 🌿 Leise ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 Leise",
                ["GpuBoostActive"] = "GPU: ⚡ Boost ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ Boost ({0}W)",
                ["TipGpuTuning"] = "GPU Leistung & Akustik-Tuning",
                ["GpuTuningTitle"] = "GPU Akustik & Leistungs-Tuning (NVIDIA)",
                ["GpuTuningEnable"] = "GPU-Tuning aktivieren",
                ["SeparateCpuGpu"] = "Getrennte CPU- & GPU-Steuerung",
                ["GpuPowerLimit"] = "Leistungslimit im Leise-Modus",
                ["GpuPowerLimitTip"] = "Begrenzt die GPU-Leistungsaufnahme zur Reduzierung von Hitze und Lüftergeräuschen",
                ["GpuFanCapEnable"] = "Akustisches GPU-Lüfterlimit",
                ["GpuFanCap"] = "Max. Lüfterdrehzahl im Leise-Modus",
                ["GpuFanCapTip"] = "Begrenzt die maximale Lüftergeschwindigkeit für flüsterleisen Betrieb",
                ["GpuFailSafeInfo"] = "🛡 Schutzfunktion: automatische Lüfterfreigabe bei {0}°C",
                ["GpuPresetEco"] = "Öko",
                ["GpuPresetQuiet"] = "Leise",
                ["GpuPresetBalanced"] = "Balance",
                ["GpuPresetStock"] = "Standard"
            },
            ["es"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "Silencioso",
                ["SilentFull"] = "🌿 Silencioso (99%)",
                ["Boost"] = "Turbo",
                ["BoostActive"] = "⚡ Turbo ACTIVO (100%)",
                ["Threads"] = "Hilos",
                ["ThreadsActive"] = "Hilos activos",
                ["AllDisksIdle"] = "Discos inactivos",
                ["Idle"] = "Inactivo",
                ["ShowAllGpus"] = "Todas las GPU",

                ["Cpu"] = "CPU",
                ["Ram"] = "RAM",
                ["Gpu"] = "GPU",
                ["Vram"] = "VRAM",
                ["Disk"] = "DISCO",
                ["Fans"] = "VENTILADORES",

                ["TipInfo"] = "Especificaciones del sistema",
                ["TipPinOn"] = "Siempre visible (Fijado)",
                ["TipPinOff"] = "Siempre visible (No fijado)",
                ["TipDetach"] = "Desacoplar widget flotante",
                ["TipDock"] = "Acoplar a bandeja del sistema",
                ["TipClose"] = "Ocultar en la bandeja",

                ["MenuGraphs"] = "Gráficos y módulos:",
                ["CpuGraph"] = "📊 Gráfico de CPU",
                ["CpuCores"] = "🔳 Mapa de núcleos CPU",
                ["TopProcesses"] = "⚡ Top 5 procesos de CPU",
                ["RamGraph"] = "🧠 Gráfico de RAM",
                ["GpuGraph"] = "🎮 Gráfico de GPU",
                ["GpuTemp"] = "🌡️ Curva de temperatura GPU",
                ["GpuFan"] = "💨 Velocidad ventilador GPU",
                ["VramGraph"] = "📼 Gráfico de VRAM",
                ["DiskGraph"] = "💽 Gráfico de Discos (SSD/HDD)",
                ["FanGraph"] = "❄️ Gráfico de ventiladores (RPM) [Addon]",
                ["ShowAllGraphs"] = "Mostrar todos los gráficos",

                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• Activo",
                ["FanPluginStatus_Connecting"] = "• Conectando...",
                ["FanPluginStatus_NotInstalled"] = "⚪ Complemento no encontrado",
                ["FanPluginStatus_Disabled"] = "Desactivado",
                ["FanPluginStatus_NeedAdmin"] = "🟡 Requiere permisos de Administrador",
                ["FanPluginStatus_NoFans"] = "No se encontraron sensores de ventilador (EC bloqueado)",
                ["FanPluginFolder"] = "Carpeta del complemento",
                ["FanPlugin_Start"] = "▶ Iniciar",
                ["FanPlugin_Stop"] = "⏹ Detener",
                ["FanPlugin_Stopped"] = "⚪ Detenido",
                ["FanPlugin_TipToggle"] = "Iniciar / detener servicio de ventiladores en segundo plano",
                ["FanVisualMode_Graph"] = "📈 Gráfico",
                ["FanVisualMode_Icons"] = "🌀 1 fila",
                ["FanVisualMode_Grid"] = "▦ Cuadrícula",
                ["FanDemoMode"] = "👁️ Demo",
                ["FanDemoModeHint"] = "Emulación (vista previa)",
                ["FanDemoModeTooltip"] = "Emulación de ventiladores para pruebas de interfaz (datos sintéticos). En portátiles los ventiladores son controlados por el EC.",
                ["FanLargeIcons"] = "Tamaño grande",
                ["FanLargeIconsTip"] = "Aumentar el tamaño de los iconos de ventilador al doble",
                ["FanScale"] = "Tamaño de ventiladores",
                ["FanScaleTip"] = "Ajustar escala de los ventiladores (100% — 200%)",
                ["FanSelectFans"] = "⚙ Ventiladores",
                ["FanSelectFansFull"] = "⚙ Seleccionar ventiladores",
                ["FanSelectionTitle"] = "Ventiladores mostrados",
                ["FanSelectionHint"] = "Seleccione los ventiladores que desea mostrar en el widget. Los ventiladores con 0 RPM pueden permanecer activos — se activarán bajo carga.",
                ["FanSelectAll"] = "Seleccionar todo",
                ["FanDeselectAll"] = "Deseleccionar todo",
                ["FanSelectionNoLiveFans"] = "No se detectaron sensores de ventilador. Inicie el servicio de ventiladores.",
                ["FanGpuSpinTest"] = "⚡ Probar ventiladores GPU (10s)",
                ["FanGpuSpinTesting"] = "⏳ Probando (10s)...",

                ["MenuSettings"] = "Configuración del sistema:",
                ["AlwaysOnTop"] = "📌 Siempre en primer plano",
                ["AutoQuiet"] = "🌿 Silencio automático en reposo (5 min)",
                ["Startup"] = "🚀 Iniciar con Windows",
                ["TrayIconMenu"] = "🏷️ Icono dinámico en bandeja",
                ["TrayMetricCpu"] = "CPU %",
                ["TrayMetricGpu"] = "GPU %",
                ["TrayMetricRam"] = "RAM %",
                ["TrayMetricNone"] = "Icono estándar",
                ["TrayMetricNoneShort"] = "Icono",
                ["BtnSpecsShort"] = "ℹ Especificaciones",
                ["Opacity"] = "👁️ Opacidad de ventana",
                ["Language"] = "🌐 Idioma / Language",
                ["HardwareInfo"] = "ℹ Especificaciones del sistema",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ Salir",

                ["InfoTitle"] = "Soporte de hardware y especificaciones",
                ["InfoDetected"] = "💻 DETECTADO EN EL SISTEMA",
                ["InfoSupported"] = "🚀 ARQUITECTURAS COMPATIBLES",
                ["InfoClose"] = "Cerrar",
                ["SysMemory"] = "Memoria del sistema",
                ["DedMemory"] = "Memoria de video dedicada",
                ["PhysicalDrives"] = "Discos físicos",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 Silencioso (99%)",
                ["CpuSilent"] = "CPU: 🌿 Silencioso",
                ["CpuBoostActive"] = "CPU: ⚡ Boost (100%)",
                ["CpuBoost"] = "CPU: ⚡ Boost",
                ["GpuSilentFull"] = "GPU: 🌿 Silencioso ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 Silencioso",
                ["GpuBoostActive"] = "GPU: ⚡ Boost ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ Boost ({0}W)",
                ["TipGpuTuning"] = "Ajuste acústico y de potencia de GPU",
                ["GpuTuningTitle"] = "Ajuste acústico y de potencia de GPU (NVIDIA)",
                ["GpuTuningEnable"] = "Habilitar ajuste de GPU",
                ["SeparateCpuGpu"] = "Control silencioso separado CPU/GPU",
                ["GpuPowerLimit"] = "Límite de potencia en modo silencioso",
                ["GpuPowerLimitTip"] = "Limita el consumo de energía de la GPU para reducir calor y ruido",
                ["GpuFanCapEnable"] = "Límite acústico de ventiladores GPU",
                ["GpuFanCap"] = "Velocidad máxima de ventilador silencioso",
                ["GpuFanCapTip"] = "Limita la velocidad máxima de los ventiladores",
                ["GpuFailSafeInfo"] = "🛡 Protección térmica: liberación automática a {0}°C",
                ["GpuPresetEco"] = "Eco",
                ["GpuPresetQuiet"] = "Silencioso",
                ["GpuPresetBalanced"] = "Balanceado",
                ["GpuPresetStock"] = "Predeterminado"
            },
            ["fr"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "Silencieux",
                ["SilentFull"] = "🌿 Silencieux (99%)",
                ["Boost"] = "Turbo",
                ["BoostActive"] = "⚡ Turbo ACTIF (100%)",
                ["Threads"] = "Threads",
                ["ThreadsActive"] = "Threads actifs",
                ["AllDisksIdle"] = "Tous disques au repos",
                ["Idle"] = "Repos",
                ["ShowAllGpus"] = "Tous les GPU",

                ["Cpu"] = "CPU",
                ["Ram"] = "RAM",
                ["Gpu"] = "GPU",
                ["Vram"] = "VRAM",
                                ["Disk"] = "DISQUE",
                ["Fans"] = "VENTILATEURS",

                ["TipInfo"] = "Spécifications du système",
                ["TipPinOn"] = "Toujours visible (Épinglé)",
                ["TipPinOff"] = "Toujours visible (Non épinglé)",
                ["TipDetach"] = "Détacher le widget flottant",
                ["TipDock"] = "Ancrer dans la barre des tâches",
                ["TipClose"] = "Masquer dans la zone de notification",

                ["MenuGraphs"] = "Graphiques & modules :",
                ["CpuGraph"] = "📊 Graphique CPU",
                ["CpuCores"] = "🔳 Grille des cœurs CPU",
                ["TopProcesses"] = "⚡ Top 5 processus CPU",
                ["RamGraph"] = "🧠 Graphique RAM",
                ["GpuGraph"] = "🎮 Graphique GPU",
                ["GpuTemp"] = "🌡️ Température GPU",
                ["GpuFan"] = "💨 Vitesse ventilateur GPU",
                ["VramGraph"] = "📼 Graphique VRAM",
                ["DiskGraph"] = "💽 Activité des disques (SSD/HDD)",
                ["FanGraph"] = "❄️ Vitesse des ventilateurs (RPM) [Module]",
                ["ShowAllGraphs"] = "Afficher tous les graphiques",

                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• Actif",
                ["FanPluginStatus_Connecting"] = "• Connexion...",
                ["FanPluginStatus_NotInstalled"] = "⚪ Module non trouvé",
                ["FanPluginStatus_Disabled"] = "Désactivé",
                ["FanPluginStatus_NeedAdmin"] = "🟡 Droits d'administrateur requis",
                ["FanPluginStatus_NoFans"] = "Aucun capteur de ventilateur trouvé (EC verrouillé)",
                ["FanPluginFolder"] = "Dossier du module",
                ["FanPlugin_Start"] = "▶ Démarrer",
                ["FanPlugin_Stop"] = "⏹ Arrêter",
                ["FanPlugin_Stopped"] = "⚪ Arrêté",
                ["FanPlugin_TipToggle"] = "Démarrer / arrêter le service d'arrière-plan des ventilateurs",
                ["FanVisualMode_Graph"] = "📈 Graphique",
                ["FanVisualMode_Icons"] = "🌀 1 ligne",
                ["FanVisualMode_Grid"] = "▦ Grille",
                ["FanDemoMode"] = "👁️ Démo",
                ["FanDemoModeHint"] = "Émulation (aperçu)",
                ["FanDemoModeTooltip"] = "Émulation de ventilateurs pour prévisualisation (données synthétiques). Sur les portables, les ventilateurs sont gérés par l'EC.",
                ["FanLargeIcons"] = "Grande taille",
                ["FanLargeIconsTip"] = "Agrandir les icônes de ventilateurs par 2",
                ["FanScale"] = "Taille des ventilateurs",
                ["FanScaleTip"] = "Ajuster l'échelle des ventilateurs (100% — 200%)",
                ["FanSelectFans"] = "⚙ Ventilateurs",
                ["FanSelectFansFull"] = "⚙ Sélectionner ventilateurs",
                ["FanSelectionTitle"] = "Ventilateurs affichés",
                ["FanSelectionHint"] = "Sélectionnez les ventilateurs à afficher dans le widget. Les ventilateurs à 0 RPM peuvent rester cochés — ils tourneront sous charge.",
                ["FanSelectAll"] = "Tout sélectionner",
                ["FanDeselectAll"] = "Tout désélectionner",
                ["FanSelectionNoLiveFans"] = "Aucun capteur détecté. Démarrez le service de ventilateurs.",
                ["FanGpuSpinTest"] = "⚡ Test ventilateurs GPU (10s)",
                ["FanGpuSpinTesting"] = "⏳ Test en cours (10s)...",

                ["MenuSettings"] = "Paramètres système :",
                ["AlwaysOnTop"] = "📌 Toujours au premier plan",
                ["AutoQuiet"] = "🌿 Mode silencieux en inactivité (5 min)",
                ["Startup"] = "🚀 Lancer au démarrage de Windows",
                ["TrayIconMenu"] = "🏷️ Icône dynamique dans la barre",
                ["TrayMetricCpu"] = "CPU %",
                ["TrayMetricGpu"] = "GPU %",
                ["TrayMetricRam"] = "RAM %",
                ["TrayMetricNone"] = "Icône standard",
                ["TrayMetricNoneShort"] = "Icône",
                ["BtnSpecsShort"] = "ℹ Spécifications",
                ["Opacity"] = "👁️ Opacité de la fenêtre",
                ["Language"] = "🌐 Langue / Language",
                ["HardwareInfo"] = "ℹ Spécifications système",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ Quitter",

                ["InfoTitle"] = "Support matériel & spécifications",
                ["InfoDetected"] = "💻 DÉTECTÉ SUR VOTRE SYSTÈME",
                ["InfoSupported"] = "🚀 ARCHITECTURES PRISES EN CHARGE",
                ["InfoClose"] = "Fermer",
                ["SysMemory"] = "Mémoire système",
                ["DedMemory"] = "Mémoire vidéo dédiée",
                ["PhysicalDrives"] = "Disques physiques",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 Silencieux (99%)",
                ["CpuSilent"] = "CPU: 🌿 Silencieux",
                ["CpuBoostActive"] = "CPU: ⚡ Boost (100%)",
                ["CpuBoost"] = "CPU: ⚡ Boost",
                ["GpuSilentFull"] = "GPU: 🌿 Silencieux ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 Silencieux",
                ["GpuBoostActive"] = "GPU: ⚡ Boost ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ Boost ({0}W)",
                ["TipGpuTuning"] = "Réglage de puissance et acoustique GPU",
                ["GpuTuningTitle"] = "Réglage acoustique et puissance GPU (NVIDIA)",
                ["GpuTuningEnable"] = "Activer le réglage GPU",
                ["SeparateCpuGpu"] = "Contrôle silencieux CPU/GPU séparé",
                ["GpuPowerLimit"] = "Limite de puissance en mode silencieux",
                ["GpuPowerLimitTip"] = "Limite la puissance du GPU pour réduire la chaleur et le bruit",
                ["GpuFanCapEnable"] = "Limite acoustique des ventilateurs GPU",
                ["GpuFanCap"] = "Vitesse maximale des ventilateurs",
                ["GpuFanCapTip"] = "Plafonne la vitesse des ventilateurs pour un silence optimal",
                ["GpuFailSafeInfo"] = "🛡 Sécurité thermique: déblocage automatique à {0}°C",
                ["GpuPresetEco"] = "Éco",
                ["GpuPresetQuiet"] = "Silencieux",
                ["GpuPresetBalanced"] = "Équilibré",
                ["GpuPresetStock"] = "Standard"
            },
            ["ja"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "静音",
                ["SilentFull"] = "🌿 静音モード (99%)",
                ["Boost"] = "ブースト",
                ["BoostActive"] = "⚡ ブースト有効 (100%)",
                ["Threads"] = "スレッド",
                ["ThreadsActive"] = "スレッド稼働中",
                ["AllDisksIdle"] = "全ディスクアイドル中",
                ["Idle"] = "アイドル",
                ["ShowAllGpus"] = "すべてのGPU",

                ["Cpu"] = "CPU",
                ["Ram"] = "RAM",
                ["Gpu"] = "GPU",
                ["Vram"] = "VRAM",
                                ["Disk"] = "ディスク",
                ["Fans"] = "ファン",

                ["TipInfo"] = "システム仕様とハードウェア情報",
                ["TipPinOn"] = "常に最前面に表示 (固定)",
                ["TipPinOff"] = "常に最前面に表示 (解除)",
                ["TipDetach"] = "デスクトップウィジェットとして分離",
                ["TipDock"] = "タスクトレイにドック",
                ["TipClose"] = "トレイに最小化",

                ["MenuGraphs"] = "グラフとモジュール:",
                ["CpuGraph"] = "📊 CPU負荷グラフ",
                ["CpuCores"] = "🔳 CPUコア稼働状況",
                ["TopProcesses"] = "⚡ CPU負荷上位5プロセス",
                ["RamGraph"] = "🧠 メモリ使用量グラフ",
                ["GpuGraph"] = "🎮 GPU負荷グラフ",
                ["GpuTemp"] = "🌡️ GPU温度推移線",
                ["GpuFan"] = "💨 GPUファン回転数",
                ["VramGraph"] = "📼 ビデオメモリグラフ",
                ["DiskGraph"] = "💽 ディスクアクセス (SSD/HDD)",
                ["FanGraph"] = "❄️ ファン回転数グラフ (RPM) [アドオン]",
                ["ShowAllGraphs"] = "すべてのグラフを表示",

                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• 稼働中",
                ["FanPluginStatus_Connecting"] = "• 接続中...",
                ["FanPluginStatus_NotInstalled"] = "⚪ アドオンが見つかりません",
                ["FanPluginStatus_Disabled"] = "無効",
                ["FanPluginStatus_NeedAdmin"] = "🟡 管理者権限が必要です",
                ["FanPluginStatus_NoFans"] = "ファンセンサーが見つかりません (ECロック)",
                ["FanPluginFolder"] = "アドオンフォルダー",
                ["FanPlugin_Start"] = "▶ 開始",
                ["FanPlugin_Stop"] = "⏹ 停止",
                ["FanPlugin_Stopped"] = "⚪ 停止済み",
                ["FanPlugin_TipToggle"] = "バックグラウンドファンサービスの開始 / 停止",
                ["FanVisualMode_Graph"] = "📈 グラフ",
                ["FanVisualMode_Icons"] = "🌀 1列",
                ["FanVisualMode_Grid"] = "▦ グリッド",
                ["FanDemoMode"] = "👁️ デモ",
                ["FanDemoModeHint"] = "エミュレーション (UIプレビュー)",
                ["FanDemoModeTooltip"] = "UIプレビュー用ファンエミュレーション（合成データ）。ノートPCのファンはECによって制御されます。",
                ["FanLargeIcons"] = "大アイコン",
                ["FanLargeIconsTip"] = "ファンスピナーアイコンのサイズを2倍に拡大",
                ["FanScale"] = "ファンサイズ",
                ["FanScaleTip"] = "ファンスピナーの拡大率を調整 (100% — 200%)",
                ["FanSelectFans"] = "⚙ ファン",
                ["FanSelectFansFull"] = "⚙ ファンを選択",
                ["FanSelectionTitle"] = "表示するファン",
                ["FanSelectionHint"] = "ウィジェットに表示するファンを選択してください。0 RPMのファンも有効のままで問題ありません（負荷時に回転します）。",
                ["FanSelectAll"] = "すべて選択",
                ["FanDeselectAll"] = "すべて解除",
                ["FanSelectionNoLiveFans"] = "ファンセンサーが検出されません。ファンサービスを開始してください。",
                ["FanGpuSpinTest"] = "⚡ GPUファンテスト (10秒)",
                ["FanGpuSpinTesting"] = "⏳ テスト実行中 (10秒)...",

                ["MenuSettings"] = "システム設定:",
                ["AlwaysOnTop"] = "📌 常に最前面に表示",
                ["AutoQuiet"] = "🌿 アイドル時自動静音 (5分)",
                ["Startup"] = "🚀 Windows起動時に自動実行",
                ["TrayIconMenu"] = "🏷️ トレイアイコンの数値表示",
                ["TrayMetricCpu"] = "CPU %",
                ["TrayMetricGpu"] = "GPU %",
                ["TrayMetricRam"] = "RAM %",
                ["TrayMetricNone"] = "標準ステータスアイコン",
                ["TrayMetricNoneShort"] = "アイコン",
                ["BtnSpecsShort"] = "ℹ ハードウェア情報",
                ["Opacity"] = "👁️ ウィンドウの不透明度",
                ["Language"] = "🌐 言語 / Language",
                ["HardwareInfo"] = "ℹ ハードウェア情報",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ 終了",

                ["InfoTitle"] = "ハードウェアサポートと仕様",
                ["InfoDetected"] = "💻 検出されたシステム構成",
                ["InfoSupported"] = "🚀 対応アーキテクチャ",
                ["InfoClose"] = "閉じる",
                ["SysMemory"] = "システムメモリ",
                ["DedMemory"] = "専用ビデオメモリ",
                ["PhysicalDrives"] = "物理ドライブ",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 静音 (99%)",
                ["CpuSilent"] = "CPU: 🌿 静音",
                ["CpuBoostActive"] = "CPU: ⚡ ブースト (100%)",
                ["CpuBoost"] = "CPU: ⚡ ブースト",
                ["GpuSilentFull"] = "GPU: 🌿 静音 ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 静音",
                ["GpuBoostActive"] = "GPU: ⚡ ブースト ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ ブースト ({0}W)",
                ["TipGpuTuning"] = "GPU電力＆静音チューニング",
                ["GpuTuningTitle"] = "GPU静音＆電力チューニング (NVIDIA)",
                ["GpuTuningEnable"] = "GPUチューニングを有効化",
                ["SeparateCpuGpu"] = "CPUとGPUの個別静音制御",
                ["GpuPowerLimit"] = "静音モード時の電力上限",
                ["GpuPowerLimitTip"] = "GPU消費電力を抑え、高負荷時の発熱とファン騒音を劇的に低減します",
                ["GpuFanCapEnable"] = "GPUファン速度上限（アコースティック制御）",
                ["GpuFanCap"] = "静音時の最大ファン回転速度",
                ["GpuFanCapTip"] = "ファンの最大回転速度を制限して静かな動作を維持します",
                ["GpuFailSafeInfo"] = "🛡 安全保護: {0}°C到達でファン制限を自動解除",
                ["GpuPresetEco"] = "エコ",
                ["GpuPresetQuiet"] = "静音",
                ["GpuPresetBalanced"] = "標準",
                ["GpuPresetStock"] = "定格"
            },
            ["pt"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "Silencioso",
                ["SilentFull"] = "🌿 Silencioso (99%)",
                ["Boost"] = "Turbo",
                ["BoostActive"] = "⚡ Turbo ATIVO (100%)",
                ["Threads"] = "Threads",
                ["ThreadsActive"] = "Threads ativas",
                ["AllDisksIdle"] = "Discos inativos",
                ["Idle"] = "Inativo",
                ["ShowAllGpus"] = "Todas as GPUs",

                ["Cpu"] = "CPU",
                ["Ram"] = "RAM",
                ["Gpu"] = "GPU",
                ["Vram"] = "VRAM",
                ["Disk"] = "DISCO",
                ["Fans"] = "VENTOINHAS",

                ["TipInfo"] = "Especificações do sistema",
                ["TipPinOn"] = "Sempre no topo (Fixado)",
                ["TipPinOff"] = "Sempre no topo (Desafixado)",
                ["TipDetach"] = "Destacar widget flutuante",
                ["TipDock"] = "Fixar na bandeja",
                ["TipClose"] = "Minimizar para a bandeja",

                ["MenuGraphs"] = "Gráficos e módulos:",
                ["CpuGraph"] = "📊 Gráfico de uso da CPU",
                ["CpuCores"] = "🔳 Matriz de núcleos da CPU",
                ["TopProcesses"] = "⚡ Top 5 processos por CPU",
                ["RamGraph"] = "🧠 Gráfico de uso da RAM",
                ["GpuGraph"] = "🎮 Gráfico de uso da GPU",
                ["GpuTemp"] = "🌡️ Curva de temperatura GPU",
                ["GpuFan"] = "💨 Ventoinhas da GPU",
                ["VramGraph"] = "📼 Gráfico de VRAM",
                ["DiskGraph"] = "💽 Atividade do Disco (SSD/HDD)",
                ["FanGraph"] = "❄️ Gráfico de ventoinhas (RPM) [Addon]",
                ["ShowAllGraphs"] = "Mostrar todos os gráficos",

                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• Ativo",
                ["FanPluginStatus_Connecting"] = "• Conectando...",
                ["FanPluginStatus_NotInstalled"] = "⚪ Complemento não encontrado",
                ["FanPluginStatus_Disabled"] = "Desativado",
                ["FanPluginStatus_NeedAdmin"] = "🟡 Direitos de administrador necessários",
                ["FanPluginStatus_NoFans"] = "Nenhum sensor de ventoinha encontrado (EC bloqueado)",
                ["FanPluginFolder"] = "Pasta do complemento",
                ["FanPlugin_Start"] = "▶ Iniciar",
                ["FanPlugin_Stop"] = "⏹ Parar",
                ["FanPlugin_Stopped"] = "⚪ Parado",
                ["FanPlugin_TipToggle"] = "Iniciar / parar serviço de ventoinhas em segundo plano",
                ["FanVisualMode_Graph"] = "📈 Gráfico",
                ["FanVisualMode_Icons"] = "🌀 1 linha",
                ["FanVisualMode_Grid"] = "▦ Grade",
                ["FanDemoMode"] = "👁️ Demo",
                ["FanDemoModeHint"] = "Emulação (pré-visualização)",
                ["FanDemoModeTooltip"] = "Emulação de ventoinhas para pré-visualização (dados sintéticos). Em notebooks, as ventoinhas são controladas pelo EC.",
                ["FanLargeIcons"] = "Tamanho grande",
                ["FanLargeIconsTip"] = "Aumentar o tamanho dos ícones das ventoinhas em 2x",
                ["FanScale"] = "Tamanho das ventoinhas",
                ["FanScaleTip"] = "Ajustar escala das ventoinhas (100% — 200%)",
                ["FanSelectFans"] = "⚙ Ventoinhas",
                ["FanSelectFansFull"] = "⚙ Selecionar ventoinhas",
                ["FanSelectionTitle"] = "Ventoinhas exibidas",
                ["FanSelectionHint"] = "Selecione as ventoinhas a serem exibidas no widget. Ventoinhas a 0 RPM podem permanecer ativas — elas girarão sob carga.",
                ["FanSelectAll"] = "Selecionar tudo",
                ["FanDeselectAll"] = "Desmarcar tudo",
                ["FanSelectionNoLiveFans"] = "Nenhum sensor detectado. Inicie o serviço de ventoinhas.",
                ["FanGpuSpinTest"] = "⚡ Testar ventoinhas GPU (10s)",
                ["FanGpuSpinTesting"] = "⏳ Testando (10s)...",

                ["MenuSettings"] = "Configurações do sistema:",
                ["AlwaysOnTop"] = "📌 Sempre no topo",
                ["AutoQuiet"] = "🌿 Modo silencioso em inatividade (5 min)",
                ["Startup"] = "🚀 Iniciar com o Windows",
                ["TrayIconMenu"] = "🏷️ Ícone dinâmico na bandeja",
                ["TrayMetricCpu"] = "CPU %",
                ["TrayMetricGpu"] = "GPU %",
                ["TrayMetricRam"] = "RAM %",
                ["TrayMetricNone"] = "Ícone padrão",
                ["TrayMetricNoneShort"] = "Ícone",
                ["BtnSpecsShort"] = "ℹ Especificações",
                ["Opacity"] = "👁️ Opacidade da janela",
                ["Language"] = "🌐 Idioma / Language",
                ["HardwareInfo"] = "ℹ Especificações do sistema",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ Sair",

                ["InfoTitle"] = "Suporte de hardware e especificações",
                ["InfoDetected"] = "💻 DETECTADO NO SISTEMA",
                ["InfoSupported"] = "🚀 ARQUITETURAS SUPORTADAS",
                ["InfoClose"] = "Fechar",
                ["SysMemory"] = "Memória do sistema",
                ["DedMemory"] = "Memória de vídeo dedicada",
                ["PhysicalDrives"] = "Discos físicos",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 Silencioso (99%)",
                ["CpuSilent"] = "CPU: 🌿 Silencioso",
                ["CpuBoostActive"] = "CPU: ⚡ Boost (100%)",
                ["CpuBoost"] = "CPU: ⚡ Boost",
                ["GpuSilentFull"] = "GPU: 🌿 Silencioso ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 Silencioso",
                ["GpuBoostActive"] = "GPU: ⚡ Boost ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ Boost ({0}W)",
                ["TipGpuTuning"] = "Ajuste acústico e de energia da GPU",
                ["GpuTuningTitle"] = "Ajuste acústico e de energia da GPU (NVIDIA)",
                ["GpuTuningEnable"] = "Ativar ajuste da GPU",
                ["SeparateCpuGpu"] = "Controle silencioso individual CPU/GPU",
                ["GpuPowerLimit"] = "Limite de potência no modo silencioso",
                ["GpuPowerLimitTip"] = "Limita o consumo da GPU para reduzir calor e ruído",
                ["GpuFanCapEnable"] = "Limite acústico dos ventiladores da GPU",
                ["GpuFanCap"] = "Velocidade máxima dos ventiladores",
                ["GpuFanCapTip"] = "Limita a rotação máxima para manter operação silenciosa",
                ["GpuFailSafeInfo"] = "🛡 Proteção térmica: liberação automática aos {0}°C",
                ["GpuPresetEco"] = "Eco",
                ["GpuPresetQuiet"] = "Silencioso",
                ["GpuPresetBalanced"] = "Equilibrado",
                ["GpuPresetStock"] = "Padrão"
            },
            ["zh"] = new()
            {
                ["AppTitle"] = "RyzenQuiet PRO v4.0",
                ["Silent"] = "静音",
                ["SilentFull"] = "🌿 静音模式 (99%)",
                ["Boost"] = "加速",
                ["BoostActive"] = "⚡ 加速开启 (100%)",
                ["Threads"] = "线程",
                ["ThreadsActive"] = "线程运行中",
                ["AllDisksIdle"] = "全部磁盘闲置",
                ["Idle"] = "空闲",
                ["ShowAllGpus"] = "所有显卡",

                ["Cpu"] = "CPU",
                ["Ram"] = "内存",
                ["Gpu"] = "显卡",
                ["Vram"] = "显存",
                ["Disk"] = "磁盘",
                ["Fans"] = "风扇",

                ["TipInfo"] = "系统规格与硬件支持",
                ["TipPinOn"] = "窗口置顶 (已固定)",
                ["TipPinOff"] = "窗口置顶 (已取消)",
                ["TipDetach"] = "分离为桌面悬浮小部件",
                ["TipDock"] = "停靠至系统托盘",
                ["TipClose"] = "最小化到托盘",

                ["MenuGraphs"] = "图表与模块:",
                ["CpuGraph"] = "📊 CPU 负载图表",
                ["CpuCores"] = "🔳 CPU 核心热力图",
                ["TopProcesses"] = "⚡ CPU 占用前 5 进程",
                ["RamGraph"] = "🧠 内存占用图表",
                ["GpuGraph"] = "🎮 显卡负载图表",
                ["GpuTemp"] = "🌡️ 显卡温度曲线",
                ["GpuFan"] = "💨 显卡风扇转速",
                ["VramGraph"] = "📼 显存占用图表",
                ["DiskGraph"] = "💽 磁盘读写活动 (SSD/HDD)",
                ["FanGraph"] = "❄️ 风扇转速图表 (RPM) [附加组件]",
                ["ShowAllGraphs"] = "显示所有图表",

                // Fan Plugin
                ["FanPluginStatus_Connected"] = "• 已激活",
                ["FanPluginStatus_Connecting"] = "• 连接中...",
                ["FanPluginStatus_NotInstalled"] = "⚪ 未找到附加组件",
                ["FanPluginStatus_Disabled"] = "已禁用",
                ["FanPluginStatus_NeedAdmin"] = "🟡 需要管理员权限",
                ["FanPluginStatus_NoFans"] = "未检测到风扇传感器 (EC被厂商锁定)",
                ["FanPluginFolder"] = "插件目录",
                ["FanPlugin_Start"] = "▶ 启动",
                ["FanPlugin_Stop"] = "⏹ 停止",
                ["FanPlugin_Stopped"] = "⚪ 已停止",
                ["FanPlugin_TipToggle"] = "启动 / 停止后台风扇监控服务",
                ["FanVisualMode_Graph"] = "📈 图表",
                ["FanVisualMode_Icons"] = "🌀 单行",
                ["FanVisualMode_Grid"] = "▦ 网格",
                ["FanDemoMode"] = "👁️ 演示",
                ["FanDemoModeHint"] = "模拟 (界面预览)",
                ["FanDemoModeTooltip"] = "用于界面预览的风扇模拟（合成数据）。笔记本风扇由EC固件控制，不向系统上报转速。",
                ["FanLargeIcons"] = "大图标",
                ["FanLargeIconsTip"] = "将风扇旋转图标放大2倍",
                ["FanScale"] = "风扇大小",
                ["FanScaleTip"] = "调节风扇图标大小 (100% — 200%)",
                ["FanSelectFans"] = "⚙ 风扇",
                ["FanSelectFansFull"] = "⚙ 选择风扇",
                ["FanSelectionTitle"] = "显示的散热风扇",
                ["FanSelectionHint"] = "勾选要在小部件中显示的风扇。0转速风扇可保持勾选，负载时会自动旋转。",
                ["FanSelectAll"] = "全选",
                ["FanDeselectAll"] = "取消全选",
                ["FanSelectionNoLiveFans"] = "未检测到活跃风扇。请启动风扇监控服务。",
                ["FanGpuSpinTest"] = "⚡ 测试显卡风扇 (10秒)",
                ["FanGpuSpinTesting"] = "⏳ 测试中 (10秒)...",

                ["MenuSettings"] = "系统设置:",
                ["AlwaysOnTop"] = "📌 窗口总在最前",
                ["AutoQuiet"] = "🌿 空闲自动静音 (5分钟)",
                ["Startup"] = "🚀 随 Windows 开机启动",
                ["TrayIconMenu"] = "🏷️ 托盘动态图标",
                ["TrayMetricCpu"] = "CPU %",
                ["TrayMetricGpu"] = "显卡 %",
                ["TrayMetricRam"] = "内存 %",
                ["TrayMetricNone"] = "标准状态图标",
                ["TrayMetricNoneShort"] = "标准图标",
                ["BtnSpecsShort"] = "ℹ 硬件规格",
                ["Opacity"] = "👁️ 窗口不透明度",
                ["Language"] = "🌐 语言 / Language",
                ["HardwareInfo"] = "ℹ 硬件规格信息",
                ["ToolsLink"] = "https://ph-cu-s.com/tools",
                ["Exit"] = "✕ 退出",

                ["InfoTitle"] = "硬件支持与系统规格",
                ["InfoDetected"] = "💻 系统检测到的硬件",
                ["InfoSupported"] = "🚀 支持的硬件架构",
                ["InfoClose"] = "关闭",
                ["SysMemory"] = "系统内存",
                ["DedMemory"] = "独立显存",
                ["PhysicalDrives"] = "物理磁盘数量",

                // GPU Tuning & Separate Controls
                ["CpuSilentFull"] = "CPU: 🌿 静音 (99%)",
                ["CpuSilent"] = "CPU: 🌿 静音",
                ["CpuBoostActive"] = "CPU: ⚡ 增强 (100%)",
                ["CpuBoost"] = "CPU: ⚡ 增强",
                ["GpuSilentFull"] = "GPU: 🌿 静音 ({0}W)",
                ["GpuSilent"] = "GPU: 🌿 静音",
                ["GpuBoostActive"] = "GPU: ⚡ 增强 ({0}W)",
                ["GpuBoost"] = "GPU: ⚡ 增强 ({0}W)",
                ["TipGpuTuning"] = "GPU功耗与静音调校",
                ["GpuTuningTitle"] = "GPU静音与功耗调校 (NVIDIA)",
                ["GpuTuningEnable"] = "启用GPU静音与功耗调校",
                ["SeparateCpuGpu"] = "CPU与GPU独立静音控制",
                ["GpuPowerLimit"] = "静音模式功耗上限",
                ["GpuPowerLimitTip"] = "限制显卡功耗以显著降低高负载时的发热与风扇噪音",
                ["GpuFanCapEnable"] = "显卡风扇声学转速限制",
                ["GpuFanCap"] = "静音模式最大风扇转速",
                ["GpuFanCapTip"] = "限制风扇最高转速以保持极致静音",
                ["GpuFailSafeInfo"] = "🛡 温度安全防护: 达 {0}°C 时自动解除风扇限制",
                ["GpuPresetEco"] = "节能",
                ["GpuPresetQuiet"] = "静音",
                ["GpuPresetBalanced"] = "均衡",
                ["GpuPresetStock"] = "出厂预设"
            }
        };

        public static void Initialize(string configuredLang)
        {
            if (string.IsNullOrWhiteSpace(configuredLang) || configuredLang.Equals("auto", StringComparison.OrdinalIgnoreCase))
            {
                string sysCode = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
                if (Strings.ContainsKey(sysCode))
                {
                    _currentLang = sysCode;
                }
                else
                {
                    _currentLang = "en";
                }
            }
            else if (Strings.ContainsKey(configuredLang.ToLowerInvariant()))
            {
                _currentLang = configuredLang.ToLowerInvariant();
            }
            else
            {
                _currentLang = "en";
            }
        }

        public static void SetLanguage(string langCode)
        {
            if (Strings.ContainsKey(langCode) && _currentLang != langCode)
            {
                _currentLang = langCode;
                LanguageChanged?.Invoke();
            }
        }

        public static string Get(string key)
        {
            if (Strings.TryGetValue(_currentLang, out var dict) && dict.TryGetValue(key, out var val))
            {
                return val;
            }
            if (Strings.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enVal))
            {
                return enVal;
            }
            return key;
        }
    }
}
